### ISSUE TITLE
Implement reference based on ISO 11649

### ISSUE THREAD

**Issue by thegnuu** [bbitgmbh/bbit.banking-utils#1]
- [ ] Implement checks
- [ ] Test checks
- [ ] Enhance validation with the new functions

See: [https://wiki.xmldation.com/General_Information/ISO11649_-_Creditor_Reference](https://wiki.xmldation.com/General_Information/ISO11649_-_Creditor_Reference)

**Comment by ghost** [comment]
I've just created this PR to help merging idea of @david-schnepf 

That's why the PR uses the already existing `node-iso11649` npm module too and add only some basic tests as `node-iso11649` already has their own tests.

**Comment by thegnuu** [comment]
Thank you @adrien-dorsaz !

It absolutely makes sense to use the existing library in that case...
I will merge your PR today.
